#!/usr/bin/env python3
"""Device-local, bounded preservation of Sileo's data during SRD UAT updates."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import re
import shutil
import stat
import sys


BUNDLE_ID = "com.amywhile.sileo"
DATA_ROOT = Path("/private/var/mobile/Containers/Data/Application")
BACKUP_ROOT = Path("/var/jb/var/lib/0sky/sileo-data-snapshots")
MAX_FILES = 10000
MAX_BYTES = 256 * 1024 * 1024
MAX_RETAINED_SNAPSHOTS = 3
SAVED_DIRS = ("Documents", "Library")
# WebKit's network cache creates hard-linked transient blobs, while SplashBoard
# owns protected launch snapshots that are regenerated by iOS and can be
# unreadable even to the SRD bootstrap. Preserve user documents and Library
# settings, but never treat either disposable tree as application data.
EXCLUDED_LIBRARY_DIRS = frozenset({"Caches", "SplashBoard"})


def _validated_snapshot(path: Path) -> tuple[int, str]:
    """Return a sortable snapshot identity after fail-closed ownership checks."""
    if (path.parent != BACKUP_ROOT or
            not re.fullmatch(r"[a-f0-9]{32}", path.name) or
            path.is_symlink() or not path.is_dir()):
        raise RuntimeError("SILEO_SNAPSHOT_RETENTION_PATH_INVALID")
    manifest_path = path / "manifest.json"
    if manifest_path.is_symlink() or not manifest_path.is_file():
        raise RuntimeError("SILEO_SNAPSHOT_RETENTION_MANIFEST_INVALID")
    try:
        manifest = json.loads(manifest_path.read_text())
    except (OSError, ValueError, UnicodeError) as error:
        raise RuntimeError("SILEO_SNAPSHOT_RETENTION_MANIFEST_INVALID") from error
    if manifest.get("bundle_id") != BUNDLE_ID or not isinstance(manifest.get("files"), dict):
        raise RuntimeError("SILEO_SNAPSHOT_RETENTION_OWNER_MISMATCH")
    for current, dirs, files in os.walk(path, followlinks=False):
        for name in dirs + files:
            if (Path(current) / name).is_symlink():
                raise RuntimeError("SILEO_SNAPSHOT_RETENTION_TREE_UNSAFE")
    return manifest_path.stat().st_mtime_ns, path.name


def prune_snapshots(keep: int = MAX_RETAINED_SNAPSHOTS) -> list[str]:
    """Remove only old, verified Sileo snapshots and retain newest ``keep``."""
    if keep < 1:
        raise ValueError("snapshot retention must keep at least one backup")
    if not BACKUP_ROOT.exists():
        return []
    if BACKUP_ROOT.is_symlink() or not BACKUP_ROOT.is_dir():
        raise RuntimeError("SILEO_SNAPSHOT_ROOT_UNSAFE")
    snapshots = []
    for path in BACKUP_ROOT.iterdir():
        # Unknown entries are preserved. Retention may delete only exact token
        # directories that prove they belong to Sileo through their manifest.
        if not re.fullmatch(r"[a-f0-9]{32}", path.name):
            continue
        snapshots.append((*_validated_snapshot(path), path))
    snapshots.sort(reverse=True)
    removed = []
    for _, token, path in snapshots[keep:]:
        shutil.rmtree(path)
        removed.append(token)
    return removed


def validate_container(path: Path) -> None:
    if path.parent != DATA_ROOT or not re.fullmatch(
            r"[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-"
            r"[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}", path.name):
        raise RuntimeError("SILEO_DATA_CONTAINER_PATH_INVALID")
    if path.is_symlink() or not path.is_dir():
        raise RuntimeError("SILEO_DATA_CONTAINER_UNAVAILABLE")
    metadata = path / ".com.apple.mobile_container_manager.metadata.plist"
    if metadata.is_symlink() or not metadata.is_file():
        raise RuntimeError("SILEO_DATA_CONTAINER_METADATA_INVALID")
    info = plistlib.loads(metadata.read_bytes())
    if info.get("MCMMetadataIdentifier") != BUNDLE_ID:
        raise RuntimeError("SILEO_DATA_CONTAINER_OWNER_MISMATCH")


def inventory(root: Path) -> dict[str, dict[str, int | str]]:
    files: dict[str, dict[str, int | str]] = {}
    total = 0
    for name in SAVED_DIRS:
        folder = root / name
        if not folder.exists():
            continue
        if folder.is_symlink() or not folder.is_dir():
            raise RuntimeError("SILEO_DATA_TREE_UNSAFE")
        for current, dirs, names in os.walk(folder, followlinks=False):
            if name == "Library" and Path(current) == folder:
                dirs[:] = [item for item in dirs if item not in EXCLUDED_LIBRARY_DIRS]
            dirs.sort()
            names.sort()
            for dirname in dirs:
                path = Path(current) / dirname
                if path.is_symlink() or not path.is_dir():
                    raise RuntimeError("SILEO_DATA_TREE_UNSAFE")
            for filename in names:
                path = Path(current) / filename
                meta = path.lstat()
                if not stat.S_ISREG(meta.st_mode) or meta.st_nlink != 1:
                    raise RuntimeError("SILEO_DATA_FILE_UNSAFE")
                total += meta.st_size
                if len(files) >= MAX_FILES or total > MAX_BYTES:
                    raise RuntimeError("SILEO_DATA_SNAPSHOT_LIMIT")
                digest = hashlib.sha256(path.read_bytes()).hexdigest()
                files[str(path.relative_to(root))] = {"size": meta.st_size,
                                                      "sha256": digest,
                                                      "mode": stat.S_IMODE(meta.st_mode)}
    return files


def backup(container: Path, token: str) -> dict:
    validate_container(container)
    if not re.fullmatch(r"[a-f0-9]{32}", token):
        raise RuntimeError("SILEO_SNAPSHOT_TOKEN_INVALID")
    files = inventory(container)
    BACKUP_ROOT.mkdir(parents=True, exist_ok=True, mode=0o700)
    if BACKUP_ROOT.is_symlink():
        raise RuntimeError("SILEO_SNAPSHOT_ROOT_UNSAFE")
    target = BACKUP_ROOT / token
    target.mkdir(mode=0o700, exist_ok=False)
    try:
        payload = target / "payload"
        payload.mkdir(mode=0o700)
        for name in SAVED_DIRS:
            source = container / name
            if source.exists():
                def ignored(path: str, names: list[str]) -> set[str]:
                    if name == "Library" and Path(path) == source:
                        return set(names) & EXCLUDED_LIBRARY_DIRS
                    return set()
                shutil.copytree(source, payload / name, symlinks=False,
                                ignore=ignored)
        if inventory(payload) != files:
            raise RuntimeError("SILEO_SNAPSHOT_COPY_MISMATCH")
        manifest = {"bundle_id": BUNDLE_ID, "files": files}
        (target / "manifest.json").write_text(json.dumps(manifest, sort_keys=True))
        os.chmod(target / "manifest.json", 0o600)
        removed = prune_snapshots()
        return {"result": "SNAPSHOT_VERIFIED", "token": token,
                "files": len(files), "bytes": sum(int(x["size"]) for x in files.values()),
                "pruned_snapshots": removed}
    except Exception:
        shutil.rmtree(target)
        raise


def restore(container: Path, token: str) -> dict:
    validate_container(container)
    if not re.fullmatch(r"[a-f0-9]{32}", token):
        raise RuntimeError("SILEO_SNAPSHOT_TOKEN_INVALID")
    target = BACKUP_ROOT / token
    if target.is_symlink() or not target.is_dir():
        raise RuntimeError("SILEO_SNAPSHOT_UNAVAILABLE")
    manifest_path = target / "manifest.json"
    if manifest_path.is_symlink() or not manifest_path.is_file():
        raise RuntimeError("SILEO_SNAPSHOT_MANIFEST_INVALID")
    manifest = json.loads(manifest_path.read_text())
    if manifest.get("bundle_id") != BUNDLE_ID:
        raise RuntimeError("SILEO_SNAPSHOT_OWNER_MISMATCH")
    payload = target / "payload"
    files = inventory(payload)
    if files != manifest.get("files"):
        raise RuntimeError("SILEO_SNAPSHOT_INTEGRITY_MISMATCH")
    owner = container.stat()
    for name in SAVED_DIRS:
        source = payload / name
        if not source.exists():
            continue
        destination = container / name
        if destination.is_symlink():
            raise RuntimeError("SILEO_RESTORE_DESTINATION_UNSAFE")
        destination.mkdir(exist_ok=True)
        os.chown(destination, owner.st_uid, owner.st_gid)
    for relative, metadata in sorted(files.items()):
        source = payload / relative
        destination = container / relative
        parents = []
        for parent in destination.parents:
            if parent == container:
                break
            parents.append(parent)
        for parent in reversed(parents):
            if parent.is_symlink():
                raise RuntimeError("SILEO_RESTORE_DESTINATION_UNSAFE")
            if not parent.exists():
                parent.mkdir()
                os.chown(parent, owner.st_uid, owner.st_gid)
        if destination.is_symlink() or (destination.exists() and not destination.is_file()):
            raise RuntimeError("SILEO_RESTORE_DESTINATION_UNSAFE")
        temporary = destination.with_name(destination.name + ".0sky-restore")
        if temporary.exists() or temporary.is_symlink():
            raise RuntimeError("SILEO_RESTORE_TEMP_EXISTS")
        with source.open("rb") as inp:
            fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                         int(metadata["mode"]))
            with os.fdopen(fd, "wb") as out:
                shutil.copyfileobj(inp, out)
                out.flush()
                os.fsync(out.fileno())
        os.chown(temporary, owner.st_uid, owner.st_gid)
        os.chmod(temporary, int(metadata["mode"]))
        os.replace(temporary, destination)
    for relative, metadata in files.items():
        path = container / relative
        if (not path.is_file() or path.is_symlink() or
                path.stat().st_size != metadata["size"] or
                hashlib.sha256(path.read_bytes()).hexdigest() != metadata["sha256"]):
            raise RuntimeError("SILEO_RESTORE_VERIFY_FAILED")
    return {"result": "DATA_RESTORED_AND_VERIFIED", "token": token,
            "files": len(files), "bytes": sum(int(x["size"]) for x in files.values())}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("backup", "restore"))
    parser.add_argument("container", type=Path)
    parser.add_argument("token")
    args = parser.parse_args()
    result = (backup if args.action == "backup" else restore)(args.container, args.token)
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
