#!/usr/bin/env python3
"""Remove generated interpreter caches from a prepared immutable release tree."""
from __future__ import annotations

import argparse
from pathlib import Path
import shutil


def prune(root: Path) -> dict[str, int]:
    root = root.resolve(strict=True)
    if not root.is_dir() or root.is_symlink():
        raise ValueError("release root must be one real directory")
    bytecode = 0
    caches = 0
    for path in sorted(root.rglob("*.py[co]"), reverse=True):
        if path.is_symlink() or not path.is_file() or root not in path.resolve().parents:
            raise ValueError("unsafe generated bytecode path")
        path.unlink()
        bytecode += 1
    for path in sorted(root.rglob("__pycache__"),
                       key=lambda item: len(item.parts), reverse=True):
        if path.is_symlink() or not path.is_dir() or root not in path.resolve().parents:
            raise ValueError("unsafe interpreter cache path")
        if any(path.iterdir()):
            raise ValueError("interpreter cache contains unexpected non-bytecode files")
        path.rmdir()
        caches += 1
    return {"bytecode_files": bytecode, "cache_directories": caches}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path)
    args = parser.parse_args()
    value = prune(args.root)
    print(f"RELEASE_CACHE_PRUNE=PASS bytecode={value['bytecode_files']} "
          f"directories={value['cache_directories']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
