#!/usr/bin/env python3
"""Developer-ID sign every macOS Mach-O in a prepared release kit.

Wheel archives are rebuilt in place with their original ZIP metadata after each
native member is signed. Their PEP 376 RECORD file and the kit wheel inventory
are then regenerated by the caller before the kit manifest is rehashed.
"""
from __future__ import annotations

import argparse
import base64
import csv
import hashlib
import io
import json
import os
from pathlib import Path
import stat
import subprocess
import tempfile
import zipfile

try:
    from .verify_release import is_macho, platform_of
except ImportError:
    from verify_release import is_macho, platform_of


def sign(path: Path, identity: str) -> None:
    result = subprocess.run(
        ["/usr/bin/codesign", "--force", "--sign", identity, "--options", "runtime",
         "--timestamp", str(path)], capture_output=True, timeout=180, check=False)
    if result.returncode:
        raise RuntimeError("codesign failed for a kit-native macOS binary")
    verified = subprocess.run(["/usr/bin/codesign", "--verify", "--strict", str(path)],
                              capture_output=True, timeout=60, check=False)
    if verified.returncode:
        raise RuntimeError("signed kit-native macOS binary failed verification")


def record_digest(path: Path) -> str:
    value = hashlib.sha256(path.read_bytes()).digest()
    return "sha256=" + base64.urlsafe_b64encode(value).rstrip(b"=").decode("ascii")


def confined_manifest_file(kit: Path, value: object) -> Path:
    """Return a real file below *kit* without following manifest symlinks."""
    if not isinstance(value, str) or not value:
        raise ValueError("runtime manifest path must be a non-empty string")
    relative = Path(value)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError("runtime manifest contains an unsafe path")
    candidate = kit
    for part in relative.parts:
        candidate /= part
        if candidate.is_symlink():
            raise ValueError("runtime manifest path must not traverse a symlink")
    try:
        resolved = candidate.resolve(strict=True)
    except (FileNotFoundError, RuntimeError) as error:
        raise ValueError("runtime manifest references a missing file") from error
    root = kit.resolve(strict=True)
    if root not in resolved.parents or not resolved.is_file():
        raise ValueError("runtime manifest path is outside the kit or is not a file")
    return resolved


def sign_wheel(wheel: Path, identity: str) -> int:
    original_mode = stat.S_IMODE(wheel.stat().st_mode)
    with zipfile.ZipFile(wheel) as source:
        infos = source.infolist()
        names = [item.filename for item in infos]
        if len(names) != len(set(names)):
            raise ValueError("wheel contains duplicate member names")
        records = [name for name in names if name.endswith(".dist-info/RECORD")]
        if len(records) != 1 or any(name.endswith((".dist-info/RECORD.jws",
                                                   ".dist-info/RECORD.p7s")) for name in names):
            raise ValueError("wheel RECORD inventory is absent, ambiguous, or signed upstream")
        with tempfile.TemporaryDirectory(prefix=".0sky-wheel-sign-", dir=wheel.parent) as folder:
            root = Path(folder)
            for info in infos:
                relative = Path(info.filename)
                mode = info.external_attr >> 16
                if (relative.is_absolute() or ".." in relative.parts or
                        stat.S_ISLNK(mode)):
                    raise ValueError("wheel contains an unsafe member")
                target = root / relative
                if info.is_dir():
                    target.mkdir(parents=True, exist_ok=True)
                    continue
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(source.read(info))
                if mode:
                    target.chmod(stat.S_IMODE(mode))
            native = 0
            for target in sorted(root.rglob("*")):
                if target.is_file() and is_macho(target) and platform_of(target) == "MACOS":
                    sign(target, identity)
                    native += 1
            if not native:
                return 0
            record = root / records[0]
            rows = []
            with record.open(newline="", encoding="utf-8") as stream:
                for row in csv.reader(stream):
                    if len(row) != 3:
                        raise ValueError("wheel RECORD row is malformed")
                    member = root / row[0]
                    if row[0] == records[0]:
                        rows.append([row[0], "", ""])
                    elif member.is_file():
                        rows.append([row[0], record_digest(member), str(member.stat().st_size)])
                    else:
                        raise ValueError("wheel RECORD references a missing member")
            rendered = io.StringIO(newline="")
            writer = csv.writer(rendered, lineterminator="\n")
            writer.writerows(rows)
            record.write_text(rendered.getvalue(), encoding="utf-8")
            fd, temporary_name = tempfile.mkstemp(prefix=".signed-wheel-", dir=wheel.parent)
            os.close(fd)
            temporary = Path(temporary_name)
            try:
                with zipfile.ZipFile(temporary, "w") as destination:
                    for info in infos:
                        if info.is_dir():
                            data = b""
                        else:
                            data = (root / info.filename).read_bytes()
                        clone = zipfile.ZipInfo(info.filename, date_time=info.date_time)
                        clone.compress_type = info.compress_type
                        clone.comment = info.comment
                        clone.extra = info.extra
                        clone.create_system = info.create_system
                        clone.create_version = info.create_version
                        clone.extract_version = info.extract_version
                        clone.flag_bits = info.flag_bits
                        clone.internal_attr = info.internal_attr
                        clone.external_attr = info.external_attr
                        destination.writestr(clone, data)
                temporary.chmod(original_mode)
                os.replace(temporary, wheel)
            finally:
                if temporary.exists():
                    temporary.unlink()
            return native


def sign_kit(kit: Path, identity: str) -> tuple[int, int]:
    kit = kit.resolve(strict=True)
    if not kit.is_dir() or kit.is_symlink():
        raise ValueError("kit must be one real directory")
    loose = 0
    for path in sorted(kit.rglob("*")):
        if (path.is_file() and not path.is_symlink() and path.suffix.lower() != ".whl"
                and is_macho(path) and platform_of(path) == "MACOS"):
            sign(path, identity)
            loose += 1
    archived = 0
    for wheel in sorted((kit / "host-mac/wheelhouse").glob("*.whl")):
        if wheel.is_symlink():
            raise ValueError("wheel must not be a symlink")
        archived += sign_wheel(wheel, identity)
    runtime_manifest = kit / "host-mac/HOST_RUNTIME_MANIFEST.json"
    value = json.loads(runtime_manifest.read_text(encoding="utf-8"))
    components = value.get("components", []) if isinstance(value, dict) else None
    if not isinstance(components, list):
        raise ValueError("runtime manifest components must be an array")
    for component in components:
        if not isinstance(component, dict):
            raise ValueError("runtime manifest component must be an object")
        component_path = confined_manifest_file(kit, component.get("path"))
        component["sha256"] = hashlib.sha256(component_path.read_bytes()).hexdigest()
        payloads = component.get("payloads") or {}
        if not isinstance(payloads, dict):
            raise ValueError("runtime manifest payloads must be an object")
        for payload in payloads.values():
            if not isinstance(payload, dict):
                raise ValueError("runtime manifest payload must be an object")
            payload_path = confined_manifest_file(kit, payload.get("path"))
            payload["sha256"] = hashlib.sha256(payload_path.read_bytes()).hexdigest()
    runtime_manifest.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n",
                                encoding="utf-8")
    return loose, archived


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("kit", type=Path)
    parser.add_argument("--identity", required=True,
                        help="Developer ID Application identity fingerprint")
    args = parser.parse_args()
    loose, archived = sign_kit(args.kit, args.identity)
    print(f"SIGNED_KIT_NATIVE_CODE=PASS loose={loose} wheel_members={archived}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
